sprint 4/step 1
luckychel/react-burger pull request #6
Opened 2024-05-01 19:56 UTC by luckychel

2024-05-10 13:27 UTC, kyzinatra commented on src/components/modal/Modal.tsx
> +
Отлично! Круто, что вы знаете про `PropsWithChildren`

2024-05-10 13:28 UTC, kyzinatra commented on src/utils/api.ts
>      return await fetch(baseUrl + url, options)
Можно лучше: options можно типизировать как `RequestInit `

2024-05-10 13:29 UTC, kyzinatra commented on src/utils/api.ts
> +export const request = async (url: string, options: any) => {
Можно лучше: `options` обычно делают не обязательным

2024-05-10 13:30 UTC, kyzinatra commented on src/components/pre-loader/PreLoader.tsx
>      return (
Надо исправить: у `style` есть встроенный тип. Вы можете наввести на свойство и посмотреть его. Стоит типизировать его верно

2024-05-10 13:31 UTC, kyzinatra commented on src/components/burger-constructor/BurgerConstructor.tsx
>           }
Надо исправить: `any` очень опасный тип, который может неявно распространяться. Не стоит его использовать. Стоит типизировать `i` правильно. Заметте, что если `ingredients` типизирован верно, то `i` не нужно типизировать вообще, как и `a, b` дальше

2024-05-10 13:32 UTC, kyzinatra commented on src/utils/types.ts
> +export interface IIngredientItem {
Можно лучше: лишние файлы лучше удалить из проекта

2024-05-10 13:33 UTC, kyzinatra commented on src/utils/api.ts
>      return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
Можно лучше: функция `checkResponse` возвращает `any`. Стоит использовать дженерик тип, чтобы типизировать его в каждом случае отдельно

2024-05-10 13:35 UTC, kyzinatra requested changes
Выглядит очень круто! Видно, что проделана большая работа. Но все же есть моменты на которые стоит обратить внимание.
Подробнее: 

**Что важно исправить:**

-  у `style` есть встроенный тип. Вы можете наввести на свойство и посмотреть его. Стоит типизировать его верно ` React.CSSProperties`
-  `any` очень опасный тип, который может неявно распространяться. Не стоит его использовать. Стоит типизировать `i` правильно. Заметте, что если `ingredients` типизирован верно, то `i` не нужно типизировать вообще, как и `a, b` дальше


**Можно лучше:**

-  options можно типизировать как `RequestInit `
-  `options` обычно делают не обязательным
-  `options` обычно делают не обязательным
-  лишние файлы лучше удалить из проекта
-  функция `checkResponse` возвращает `any`. Стоит использовать дженерик тип, чтобы типизировать его в каждом случае отдельно


**Что понравилось:**

-  Круто, что вы знаете про `PropsWithChildren`


**Обратите внимание, что работа принимается только после исправления всех `«Надо исправить»`.**

2024-05-10 19:33 UTC, luckychel commented on src/utils/api.ts
>      return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
тут столько вариантов может быть, пришлите пример как сделать пожалуйста

2024-05-10 19:35 UTC, luckychel commented on src/utils/types.ts
> +export interface IIngredientItem {
не совсем понял, что нужно удалить?
файл src/utils/types.ts точно не лишний

2024-05-10 19:35 UTC, luckychel commented on src/components/burger-constructor/BurgerConstructor.tsx
>           }
исправил вроде бы

2024-05-10 19:35 UTC, luckychel commented on src/components/pre-loader/PreLoader.tsx
>      return (
спасибо, да, так намного лучше

2024-05-10 19:36 UTC, luckychel commented on src/utils/api.ts
> +export const request = async (url: string, options: any) => {
спасибо, сделал и даже лучше)

2024-05-10 19:36 UTC, luckychel commented on src/utils/api.ts
>      return await fetch(baseUrl + url, options)
спасибо. так стало лучше

2024-05-10 19:36 UTC, luckychel commented on src/components/modal/Modal.tsx
> +
спасибо

2024-05-10 20:28 UTC, kyzinatra commented on src/utils/types.ts
> +export interface IIngredientItem {
К сожалению не смог написать это прям в лишнем файле, посколькльку вы него не меняли. Я про файлы с мокрыми данными и типизацией proptypes. Вы же уже не используете их

2024-05-10 20:29 UTC, kyzinatra commented on src/utils/api.ts
>      return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
Я говорю про дженерик тип к примеру

```js
function <T>checkResponse(res: Response): Promise<T>

```

И использовать как `checkResponse<MySuperTypeN>`

2024-05-11 08:21 UTC, kyzinatra commented
Вы отлично потрудились.
Поздравляю! Ваша работа принята.
Удачного дальнейшего обучения.

2024-05-11 09:45 UTC, luckychel commented on src/utils/api.ts
>      return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
Спасибо, изучу данный вопрос

2024-05-11 09:48 UTC, luckychel commented on src/utils/types.ts
> +export interface IIngredientItem {
Понял, да можно удалить теперь

2024-05-11 20:06 UTC, merged